import pandas as pd
df=pd.read_csv("amazon_sales_dataset.csv")
print("Dataset loaded successfully")
print(df.head())
print(df.info())
print(df.describe())
print(df.isnull().sum())
print("Duplicated:",df.duplicated().sum())
df=df.drop_duplicates()
df.to_csv("cleaned_sales_data.csv",index=False)
print("Cleaned file saved successfully")
print("\n--- DATA QUALITY REPORT ---")
print("\nMissing Values:")
print(df.isnull().sum())
print("\nDuplicate Rows:")
print(df.duplicated().sum())
print("\nDataset Shape (rows, columns):")
print(df.shape)
df.to_csv("cleaned_sales_data.csv",index=False)
print("Cleaned dataset saved successfully")
print("\n--- FINAL REPORT ---")
print("Total Rows:",len(df))
print("Total Columns:",len(df.columns))
print("\nColumn Names:")
print(df.columns)


if "brand" in df.columns:
    print("\nTop Brands:")
    print(df["brand"].value_counts().head(10))

print("\n--- SALES SUMMARY---")
print("Columns:",df.columns)
df["Total Sales"]=df["Total Sales"].astype(str)
df["Total Sales"]=df["Total Sales"].str.replace(",","")
df["Total Sales"]=df["Total Sales"].str.replace("$","")
df["Total Sales"]=pd.to_numeric(df["Total Sales"],errors="coerce")
print("Total Sales:",df["Total Sales"].sum())
print("Average Sales:",df["Total Sales"].mean())

import matplotlib.pyplot as plt
if "brand" in df.columns:
    top_brands=df["brand"].value_counts().head(10)
    top_brands.plot(kind="bar")
    plt.title("TOP 10 BRANDS BY COUNT")
    plt.xlabel("Brand")
    plt.ylabel("Count")
    plt.xticks(rotation=45)
    plt.savefig("top_brands.png")
    plt.show()
    plt.figure()
    df["Total Sales"].dropna().plot(kind="hist",bins=10)
    plt.title("SALES DISTRIBUTION")
    plt.savefig("sales_distribution.png")
    plt.show()